AWSTemplateFormatVersion: "2010-09-09"
Description: Run at new account creation
Parameters:
    userName:
        Type: String
        Description: The main user name

Resources:
    userAccount:
        Type: AWS::IAM::User
        Properties: 
            Groups: 
                - administrators
            UserName: !Ref userName

    securityGroup: 
        Type: AWS::EC2::SecurityGroup
        Properties: 
            GroupDescription: !Sub "SecurityGroup for ${userName}"
            GroupName: !Sub "individual-${userName}"
    
    

    cloud9EC2EnvUser:
        Type: AWS::Cloud9::EnvironmentEC2
        Properties: 
            InstanceType: t2.micro
            Name: !Sub "${userName} Cloud9"
            OwnerArn: !GetAtt userAccount.Arn
