AWSTemplateFormatVersion: "2010-09-09"
Description: Run at new account creation
Parameters:
    userName:
        Type: String
        Description: The main user name
    subnetId:
        Type: AWS::EC2::Subnet::Id
        Description: The subnetId
    vpcId:
        Type: AWS::EC2::VPC::Id
        Description: The VPC for the SecurityGroup

Resources:
    userAccount:
        Type: AWS::IAM::User
        Properties: 
            Groups: 
                - administrators
            UserName: !Ref userName

    securityGroup: 
        Type: AWS::EC2::SecurityGroup
        Properties: 
            GroupDescription: !Sub "SecurityGroup for ${userName}"
            GroupName: !Sub "individual-${userName}"
            SecurityGroupEgress:
                - CidrIp: 127.0.0.1/32
                  IpProtocol: "-1"
            VpcId: !Ref vpcId
    
    

    cloud9EC2EnvUser:
        Type: AWS::Cloud9::EnvironmentEC2
        Properties: 
            InstanceType: t2.micro
            Name: !Sub "${userName} Cloud9"
            OwnerArn: !GetAtt userAccount.Arn
            SubnetId: !Ref subnetId
