AWSTemplateFormatVersion: "2010-09-09"
Description: Other resources for new account creation
Resources:
    loggingBucket:
        Type: AWS::S3::Bucket
        Properties: 
            AccessControl: LogDeliveryWrite
            BucketName: 'loggingbucket.imperial.galactic.gov'
            LifecycleConfiguration: 
                Rules: 
                    - ExpirationInDays: 1
                      Id: !Sub '${AWS::StackName}-objectExpire'
                      Status: Enabled
                      
    terrraformStateFileBucket:
        Type: AWS::S3::Bucket
        Properties: 
            BucketName: 'terraform-state.imperial.galactic.gov'
            VersioningConfiguration: 
                Status: Enabled
            LoggingConfiguration:
                DestinationBucketName: !Ref loggingBucket
                LogFilePrefix: 'terraform-state/'
                
            
            
Outputs:
    loggingBucketName:
        Value: !Ref loggingBucket
        Export: 
            Name: logging-bucket-name
    loggingBucketArn:
        Value: !GetAtt loggingBucket.Arn
        Export: 
            Name: logging-bucket-arn