AWSTemplateFormatVersion: "2010-09-09"
Description: Other resources for new account creation
Resources:
    logging:
        Type: AWS::S3::Bucket
        Properties: 
            BucketName: !Sub '${AWS::StackName}-loggingbucket.imperial.galactic.gov'
            
            LifecycleConfiguration: 
                Rules: 
                    - ExpirationInDays: 10
                      Id: !Sub '${AWS::StackName}-objectExpire'
                      Status: Enabled
