AWSTemplateFormatVersion: "2010-09-09"
Description: Run at new account creation
Resources:
    configS3bucket:
        Type: AWS::S3::Bucket
        Properties: 
            BucketName: !Sub '${AWS::StackName}.imperial.galactic.gov'
            LifecycleConfiguration: 
                Rules: 
                    - ExpirationInDays: 30
                      Id: !Sub '${AWS::StackName}-objectExpire'
                      Status: Enabled
    snsTopic:
        Type: AWS::SNS::Topic
        Properties: 
            DisplayName: An SNS Topic for all simple monitoring
            Subscription: 
                -
                    Endpoint: motescj@gmail.com
                    Protocol: email 
            TopicName: !Sub '${AWS::StackName}-alerts'
    cloudTrail:
        Type: AWS::CloudTrail::Trail
        Properties: 
            IsMultiRegionTrail: True
            S3BucketName: !Sub '${AWS::StackName}.imperial.galactic.gov'
            S3KeyPrefix: /cloudTrail/
            SnsTopicName: !Sub '${AWS::StackName}-alerts'
            TrailName: !Sub '${AWS::StackName}-allregion'