AWSTemplateFormatVersion: "2010-09-09"
Description: Run at new account creation
Resources:
    configS3bucket:
        Type: AWS::S3::Bucket
        Properties: 
            BucketName: !Sub '${AWS::StackName}.imperial.galactic.gov'
            LifecycleConfiguration: 
                Rules: 
                    - ExpirationInDays: 30
                      Id: !Sub '${AWS::StackName}-objectExpire'
                      Status: Enabled
    snsTopic:
        Type: AWS::SNS::Topic
        Properties: 
            DisplayName: An SNS Topic for all simple monitoring
            Subscription: 
                -
                    Endpoint: motescj@gmail.com
                    Protocol: email 
            TopicName: !Sub '${AWS::StackName}-alerts'
    cloudTrailSNSPolicy:
        Type: AWS::SNS::TopicPolicy
        Properties: 
            PolicyDocument: 
                Version: "2012-10-17"
                Statement:
                        Sid: AWSCloudTrailSNSPolicy20131101
                        Effect: Allow
                        Principal: {"Service": "cloudtrail.amazonaws.com"}
                        Action: SNS:Publish
                        Resource: !Ref snsTopic
            Topics: 
                - !Ref snsTopic

    cloudTrailBucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties: 
            Bucket: !Sub '${AWS::StackName}.imperial.galactic.gov'
            PolicyDocument: 
                Version: "2012-10-17"
                Statement: 
                    - 
                        Sid: "AWSCloudTrailAclCheck20150319"
                        Effect: "Allow"
                        Principal: {"Service": "cloudtrail.amazonaws.com"}
                        Action: "s3:GetBucketAcl"
                        Resource: !GetAtt configS3bucket.Arn
                    -
                        Sid: "AWSCloudTrailWrite20150319"
                        Effect: "Allow"
                        Principal: {"Service": "cloudtrail.amazonaws.com"}
                        Action: "s3:PutObject"
                        Resource: !Sub 'arn:aws:s3:::${AWS::StackName}.imperial.galactic.gov/cloudTrail/AWSLogs/${AWS::AccountId}/*'
                        Condition: {"StringEquals": {"s3:x-amz-acl": "bucket-owner-full-control"}}
    cloudTrailCloudWatchLogs:
        Type: AWS::Logs::LogGroup
        Properties: 
          LogGroupName: cloudtrail
          RetentionInDays: 3
    cloudTrailRole:
        Type: AWS::IAM::Role
        Properties: 
            AssumeRolePolicyDocument: 
                Version: 2012-10-17
                Statement: 
                     -
                        Effect: Allow
                        Principal: { "Service": "cloudtrail.amazonaws.com" }
                        Action: sts:AssumeRole
            Description: Role for CloudTrail
            Policies:
                - 
                    PolicyName: "CloudTrailToCWLogs"
                    PolicyDocument:
                        Version: 2012-10-17
                        Statement: 
                            -
                                Effect: Allow
                                Action:  logs:CreateLogStream
                                Resource:  !GetAtt cloudTrailCloudWatchLogs.Arn
                            - 
                                Effect: Allow
                                Action:  logs:PutLogEvents
                                Resource:  !GetAtt cloudTrailCloudWatchLogs.Arn
            RoleName: !Sub '${AWS::StackName}-cloudtrail'
    cloudTrail:
        Type: AWS::CloudTrail::Trail
        DependsOn: 
            - cloudTrailBucketPolicy
            - cloudTrailSNSPolicy
        Properties: 
            CloudWatchLogsLogGroupArn: !GetAtt cloudTrailCloudWatchLogs.Arn
            CloudWatchLogsRoleArn: !GetAtt cloudTrailRole.Arn
            IncludeGlobalServiceEvents: True
            IsLogging: False
            IsMultiRegionTrail: True
            S3BucketName: !Sub '${AWS::StackName}.imperial.galactic.gov'
            S3KeyPrefix: cloudTrail
            TrailName: !Sub '${AWS::StackName}-allregion'
    terrraformStateFileBucket:
        Type: AWS::S3::Bucket
        Properties: 
            BucketName: !Sub '${AWS::StackName}-terraform-state.imperial.galactic.gov'
            VersioningConfiguration: 
                      Status: Enabled